Automated publishing
SilkMC/silk pull request #71
Opened 2024-12-23 16:02 UTC by kxmpxtxnt

2024-12-23 16:03 UTC, kxmpxtxnt commented
Todo:
- Add tokens/secret via cli parameters from github secretes

2024-12-23 16:14 UTC, kxmpxtxnt commented on .github/workflows/full-publish.yaml
> +          java-version: "11"
I'm also unsure about this part. 
I have no idea if this works or if we need some other action

2024-12-24 11:48 UTC, kxmpxtxnt commented
More a general question but I think it wouldn't be bad if we had a second target for publishing besides maven central to release hotfixes or small insignificant updates.

2024-12-24 16:15 UTC, jakobkmar commented
> More a general question but I think it wouldn't be bad if we had a second target for publishing besides maven central to release hotfixes or small insignificant updates.

You mean for snapshots? Hotfixes should also be deployed to maven central in my opinion.

But yes, maven central also provides a separate snapshot repo, which can be used for that.

2024-12-24 21:19 UTC, kxmpxtxnt commented
> > More a general question but I think it wouldn't be bad if we had a second target for publishing besides maven central to release hotfixes or small insignificant updates.
> 
> You mean for snapshots? Hotfixes should also be deployed to maven central in my opinion.
> 
> But yes, maven central also provides a separate snapshot repo, which can be used for that.

Oh, I didn't know about the snapshot repo

2025-01-19 16:26 UTC, jakobkmar requested changes

2025-01-19 16:26 UTC, jakobkmar commented on .github/workflows/publishing.yml
> +          java-version: "11"
the latest LTS version is required for Minecraft development

2025-01-19 16:44 UTC, jakobkmar approved these changes

2025-01-19 16:45 UTC, merged